# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-01-09 08:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reinforce', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reinforce',
            new_name='Learning',
        ),
    ]
