# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-01-09 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reinforce', '0002_auto_20190109_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learning',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
