# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-26 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithem',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
