# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-02 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0004_finishedalgorithem'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='remote_report_path',
            field=models.CharField(default='', max_length=255),
        ),
    ]
