# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-02 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0005_strategy_remote_report_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithem',
            name='obvious_param',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='finishedalgorithem',
            name='obvious_param',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='strategy',
            name='obvious_param',
            field=models.CharField(default='', max_length=255),
        ),
    ]
