# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-26 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('user_type', models.SmallIntegerField(default=1, max_length=1)),
            ],
        ),
    ]
