# -*- coding: UTF-8 -*-
# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-21 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20181026_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('user', models.CharField(max_length=64)),
                ('amount', models.IntegerField()),
                ('stock_id', models.CharField(max_length=64)),
                ('order_time', models.DateTimeField(max_length=64)),
                ('order_price', models.FloatField(max_length=64)),
                ('order_type', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.IntegerField(db_index=True, max_length=64, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AddField(
            model_name='user',
            name='api_key',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
