# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-23 05:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20181121_2017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Strategy',
        ),
    ]
