# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-27 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0002_auto_20181226_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='algorithem',
            old_name='email',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='strategy',
            old_name='email',
            new_name='user',
        ),
    ]
