# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-02 07:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_delete_strategy'),
        ('strategy', '0003_auto_20181227_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedAlgorithem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('timestamp', models.CharField(default='', max_length=255)),
                ('traded_list', models.CharField(default='', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.User')),
            ],
        ),
    ]
